name: my_reading_app
description: Manga Studio Ultimate by Tin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  photo_view: ^0.15.0 
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2 # Lưu dữ liệu vào máy

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/chapters/chap1/
    # Khi Tín thêm thư mục mới (ví dụ chap2), phải khai báo thêm ở đây