name: my_reading_app
description: Ung dung Manga Studio ProMax cua Tin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  photo_view: ^0.15.0 
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2 # De luu du lieu Manga da tao
  path_provider: ^2.1.2 # De quan ly duong dan file/thu muc

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/chapters/chap1/ # Giu lai de lam du lieu mau