name: my_reading_app
description: Ứng dụng đọc truyện tranh Manga của Tín.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0' # Hỗ trợ phiên bản Flutter 3.38.9 bạn đang dùng

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Thư viện hỗ trợ phóng to/thu nhỏ ảnh khi đọc truyện tranh
  photo_view: ^0.15.0 
  # Thư viện giúp tải ảnh từ mạng mượt mà hơn
  cached_network_image: ^3.3.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Công cụ tự động tạo icon cho ứng dụng
  flutter_launcher_icons: ^0.13.1 

# Cấu hình icon ứng dụng
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png" # Đường dẫn đến file ảnh bạn vừa tạo
  remove_alpha_ios: true # Quan trọng để Apple không báo lỗi icon bị trong suốt

flutter:
  uses-material-design: true

  # Khai báo thư mục chứa ảnh để Flutter nhận diện
  assets:
    - assets/images/icon.png